name: Build and Test

on:
  push:
    paths:
      - 'auth-service'
      - 'auth-service/**'
      - 'product-service'
      - 'product-service/**'
      - 'order-service'
      - 'order-service/**'
      - 'inventory-service'
      - 'inventory-service/**'
      - 'payment-service'
      - 'payment-service/**'
      - 'ui-service'
      - 'ui-service/**'
      - '.github/workflows/build.yml'
      - 'readme.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - auth-service
          - product-service
          - order-service
          - inventory-service
          - payment-service
          - ui-service

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          cache-dependency-path: |
            **/pom.xml

      - name: Build and Test
        run: mvn clean verify
        working-directory: ${{ matrix.service }}

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ${{ matrix.service }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          verbose: true
          fail_ci_if_error: false
